### PR TITLE
Swift 3.0

### PR DESCRIPTION
**Pull request by angerman**
This essentially merges the changes from @maarf, and updated the podspec to 4.0 to be in line with argo.

### CODE REVIEW

**Comment by edwardaux** [comment]
Hey @angerman ... thanks for pulling these together. Just trying to wrap my head around all the changes in here. At a high level, it looks like:
- Swift 2.3 -> 3.0 migration
- Version bump to 4.0
- Removal of Argo as a submodule
- Now doesn't check in anything at all into the Carthage folder

The first two totally make sense. 

I guess that the 3rd one is to try and workaround https://github.com/thoughtbot/Argo/issues/412 which was currently holding up my own port to Swift 3.0. Is that right?

Curious as to why the setting was changed for `.gitignore`. Could you elaborate a bit please?

Thanks!

**Comment by angerman** [comment]
@edwardaux to be honest, I just checked the Fork graph and merged together the relevant branches to get me a swift3 compatible orgra I could use with argo 4.0.

I don't actually claim ownership of any of this code, it's all @mitsuse's and @maaf's awesome work; I could possibly drop all the carthage stuff from this, and make this a swift3, cocoapods only pr?

**Sidenote**: I'm using this as cocoapod and can't really elaborate on the carthage part :-/

**Comment by maarf** [comment]
@edwardaux The change to `.gitignore` was a result of not using Carthage with `--use-submodules` because of problems with Xcode 8 that I can’t quite recall anymore.

**Comment by maarf** [comment]
Oh yes, it was thoughtbot/Argo#412 why I removed Carthage submodules and added the whole `Carthage` directory to `.gitignore` otherwise Carthage checkouts would be committed too. Seems that the underlying issue is still open.

**Comment by maarf** [comment]
This one should be added too: https://github.com/maarf/Ogra/commit/5501b7eefad3f3958552f64c676a7d053dfa4060

**Comment by maarf** [comment]
This one should be merged in too: https://github.com/maarf/Ogra/commit/a9979008163b4d5ec107bb11688fbdc19fc1d7b5

**Pull request merged**
