### PR TITLE
Adds podspec

### PR DESCRIPTION
**Pull request by angerman**
This would allow to use Ogra with cocoapods.

### CODE REVIEW

**Comment by paulyoung** [comment]
Hey @angerman!

Ogra [currently depends on the `td-swift-2` branch of Argo](https://github.com/edwardaux/Ogra/blob/6dd6a4cff25ee66db6e369d1e42ebd2c8cf02750/Cartfile#L1) but I didn't see a mention of that here.

How is that handled?

**Comment by angerman** [comment]
Yes it does; cocoapods podspec do not allow to set git/branch dependencies to my knowledge.  All I've seen so far is, that this is usually handled by the Podfile referencing the pod as in

```
  pod 'Runes', :git => 'https://github.com/thoughtbot/Runes.git'
  pod 'Argo', :git => 'https://github.com/angerman/Argo.git', :branch => 'td-swift-2', :submodules => true
  pod 'Ogra', :git => 'https://github.com/angerman/Ogra.git'
```

which works.

Since the advert of `swift 2`, a lot of pods currently require the use of `:branch =>` in the Podspec.

**Comment by edwardaux** [comment]
Thanks for the PR. Crazy swamped at work at the moment, but will look into it ASAP.

**Comment by edwardaux** [comment]
Hi @angerman, looks fine to me except that the summary is `Sync capabilities for Realm` :)

Maybe something like `Provides the ability to convert from a model object into an Argo JSON representation.`

**Comment by angerman** [comment]
@edwardaux good catch! Sorry for that. Fixed.

**Pull request merged**
